import type { Book } from '@/types/core';
import type { ArticleCardData } from '@/components/ArticleCard';
import type { CollectionCardData } from '@/components/CollectionCard';
import type { ReviewCardData } from '@/components/ReviewCard';
import type { CurrentlyReadingItem } from '@/components/home/CurrentlyReadingSection/CurrentlyReadingSection';

export const mockCarouselBooks: Book[] = [
  {
    id: '3',
    title: 'Мастер и Маргарита',
    author: 'Михаил Булгаков',
    year: 1967,
    genres: ['Роман'],
    description: 'Сатира и мистический роман.',
    coverUrl: 'https://cdn.azbooka.ru/cv/w1100/98fa6b42-e86d-4f17-9376-25e98cc784e5.jpg',
    pagesCount: 410,
    status: { verified: true },
    createdBy: 'u1',
    createdAt: '2026-01-03',
    tags: [],
    ratings: { average: 9.0, count: 3102 },
  },
  {
    id: '2',
    title: 'Преступление и наказание',
    author: 'Фёдор Достоевский',
    year: 1866,
    genres: ['Психология'],
    description: 'История внутреннего кризиса.',
    coverUrl: undefined,
    pagesCount: 560,
    status: { verified: true },
    createdBy: 'u1',
    createdAt: '2026-01-02',
    tags: [],
    ratings: { average: 9.1, count: 2305 },
  },
  {
    id: '4',
    title: 'Отверженные',
    author: 'Виктор Гюго',
    year: 1862,
    genres: ['Исторический'],
    description: 'Эпический роман о милосердии.',
    coverUrl: 'https://cdn.azbooka.ru/cv/w1100/8e4f70bd-f412-4f3c-a9cf-b1755601fb97.jpg',
    pagesCount: 1240,
    status: { verified: true },
    createdBy: 'u1',
    createdAt: '2026-01-04',
    tags: [],
    ratings: { average: 8.9, count: 980 },
  },
  {
    id: '1',
    title: 'Отцы и дети',
    author: 'Иван Тургенев',
    year: 1862,
    genres: ['Роман'],
    description: 'Роман о конфликте поколений.',
    coverUrl: undefined,
    pagesCount: 320,
    status: { verified: true },
    createdBy: 'u1',
    createdAt: '2026-01-01',
    tags: [],
    ratings: { average: 8.6, count: 1240 },
  },
  {
    id: '7',
    title: 'Гарри Поттер и философский камень',
    author: 'Дж. К. Роулинг',
    year: 1997,
    genres: ['Фантастика'],
    description: 'Начало школьного приключения.',
    coverUrl: undefined,
    pagesCount: 336,
    status: { verified: true },
    createdBy: 'u1',
    createdAt: '2026-01-07',
    tags: [],
    ratings: { average: 8.8, count: 8022 },
  },
  {
    id: '5',
    title: 'Норвежский лес',
    author: 'Харуки Мураками',
    year: 1987,
    genres: ['Драма'],
    description: 'Тихий роман о взрослении.',
    coverUrl: undefined,
    pagesCount: 384,
    status: { verified: true },
    createdBy: 'u2',
    createdAt: '2026-01-05',
    tags: [],
    ratings: { average: 8.1, count: 1405 },
  },
  {
    id: '9',
    title: 'Маленький принц',
    author: 'Антуан де Сент-Экзюпери',
    year: 1943,
    genres: ['Философия'],
    description: 'Сказка-притча о дружбе.',
    coverUrl: undefined,
    pagesCount: 96,
    status: { verified: true },
    createdBy: 'u1',
    createdAt: '2026-01-09',
    tags: [],
    ratings: { average: 8.7, count: 10020 },
  },
  {
    id: '6',
    title: 'Великий Гэтсби',
    author: 'Фрэнсис Скотт Фицджеральд',
    year: 1925,
    genres: ['Роман'],
    description: 'История мечты и разочарования.',
    coverUrl: undefined,
    pagesCount: 180,
    status: { verified: true },
    createdBy: 'u1',
    createdAt: '2026-01-06',
    tags: [],
    ratings: { average: 8.3, count: 2011 },
  },
  {
    id: '8',
    title: 'Фауст',
    author: 'Иоганн Вольфганг фон Гёте',
    year: 1808,
    genres: ['Поэзия'],
    description: 'Трагедия о поиске смысла.',
    coverUrl: undefined,
    pagesCount: 240,
    status: { verified: true },
    createdBy: 'u2',
    createdAt: '2026-01-08',
    tags: [],
    ratings: { average: 8.0, count: 650 },
  },
];

export const mockNewReleases: CurrentlyReadingItem[] = [
  { id: '3', title: 'Мастер и Маргарита', genre: 'Роман', coverUrl: 'https://cdn.azbooka.ru/cv/w1100/98fa6b42-e86d-4f17-9376-25e98cc784e5.jpg' },
  { id: '2', title: 'Преступление и наказание', genre: 'Психология' },
  { id: '9', title: 'Маленький принц', genre: 'Философия' },
];

export const mockGainingPopularity: CurrentlyReadingItem[] = [
  { id: '4', title: 'Отверженные', genre: 'Исторический', coverUrl: 'https://cdn.azbooka.ru/cv/w1100/8e4f70bd-f412-4f3c-a9cf-b1755601fb97.jpg' },
  { id: '1', title: 'Отцы и дети', genre: 'Роман' },
  { id: '5', title: 'Норвежский лес', genre: 'Драма' },
];

export const mockPopular: CurrentlyReadingItem[] = [
  { id: '7', title: 'Гарри Поттер и философский камень', genre: 'Фантастика' },
  { id: '6', title: 'Великий Гэтсби', genre: 'Роман' },
  { id: '8', title: 'Фауст', genre: 'Поэзия' },
];

export const mockArticleCards: ArticleCardData[] = [
  {
    id: 'a1',
    title: 'Стоит ли читать «Преступление и наказание»?',
    excerpt: 'Если ты откладывал из-за "тяжести" — вот честная карта: почему это читается быстрее, чем кажется, и что ты получишь в конце.',
    categoryLabel: 'Стоит ли читать?',
    author: { name: 'Мария Петрова', avatarUrl: 'https://i.pravatar.cc/150?u=maria' },
    createdAt: '26 января, 2026',
    rating: 4.8,
    upvotes: 142,
  },
  {
    id: 'a2',
    title: 'Разбор: конфликт "отцов и детей" как спор о языке будущего',
    excerpt: 'Не про "плохих родителей" и "дерзкую молодежь": конфликт тут о том, кто имеет право на смысл.',
    categoryLabel: 'Разборы',
    author: { name: 'Алексей Иванов', avatarUrl: 'https://i.pravatar.cc/150?u=alexey' },
    createdAt: '20 января, 2026',
    rating: 4.5,
    upvotes: 96,
  },
  {
    id: 'a6',
    title: 'Гайд: как читать длинный роман и не сдаться на середине',
    excerpt: 'Три стратегии: карта персонажей, ритм чтения и "точки удержания" — чтобы огромный текст стал управляемым.',
    categoryLabel: 'Гайды',
    author: { name: 'Дмитрий Соколов', avatarUrl: 'https://i.pravatar.cc/150?u=dmitry' },
    createdAt: '10 января, 2026',
    rating: 4.3,
    upvotes: 77,
  },
  {
    id: 'a8',
    title: 'Сравнение: «Великий Гэтсби» — роман про любовь или про статус?',
    excerpt: 'Смотрим на текст как на систему сигналов: что герои показывают друг другу и что скрывают.',
    categoryLabel: 'Сравнения',
    author: { name: 'Мария Петрова', avatarUrl: 'https://i.pravatar.cc/150?u=maria' },
    createdAt: '22 января, 2026',
    rating: 4.1,
    upvotes: 41,
  },
];

export const mockHomeReviews: ReviewCardData[] = [
  {
    id: 'rc4',
    status: 'completed',
    title: 'Преступление и наказание - глубокий психологический анализ',
    description: 'Невероятно мощное произведение Достоевского. Раскольников - один из самых сложных персонажей.',
    author: { name: 'Алексей Иванов', avatarUrl: 'https://i.pravatar.cc/150?u=alexey' },
    createdAt: '3 дня назад',
    upvotes: 45,
    commentsCount: 18,
    category: 'Классика',
    isUpvoted: true,
  },
  {
    id: 'rc5',
    status: 'completed',
    title: 'Мастер и Маргарита - шедевр Булгакова',
    description: 'Книга, которая открывается с каждым прочтением по-новому. Сатира, мистика, любовь.',
    author: { name: 'Мария Петрова', avatarUrl: 'https://i.pravatar.cc/150?u=maria' },
    createdAt: '1 неделю назад',
    upvotes: 67,
    commentsCount: 31,
    category: 'Классика',
    isUpvoted: false,
  },
  {
    id: 'rc6',
    status: 'draft',
    title: '1984 - актуальность в современном мире',
    description: 'Оруэлл предсказал многое из того, что мы видим сегодня. Тотальный контроль, манипуляция.',
    author: { name: 'Дмитрий Соколов', avatarUrl: 'https://i.pravatar.cc/150?u=dmitry' },
    createdAt: '5 дней назад',
    upvotes: 32,
    commentsCount: 15,
    category: 'Антиутопия',
    isUpvoted: false,
  },
    {
    id: 'rc6',
    status: 'draft',
    title: '1984 - актуальность в современном мире',
    description: 'Оруэлл предсказал многое из того, что мы видим сегодня. Тотальный контроль, манипуляция.',
    author: { name: 'Дмитрий Соколов', avatarUrl: 'https://i.pravatar.cc/150?u=dmitry' },
    createdAt: '5 дней назад',
    upvotes: 32,
    commentsCount: 15,
    category: 'Антиутопия',
    isUpvoted: false,
  },
];

export const mockCollections: CollectionCardData[] = [
  {
    id: 'col1',
    title: 'Русская классика: обязательные к прочтению',
    lastEditedAt: 'Обновлено 3 дня назад',
    views: 1240,
    booksCount: 12,
    bookmarks: 89,
  },
  {
    id: 'col2',
    title: 'Лучшие философские романы',
    lastEditedAt: 'Обновлено 1 неделю назад',
    views: 870,
    booksCount: 8,
    bookmarks: 56,
  },
  {
    id: 'col3',
    title: 'Книги для долгих вечеров',
    lastEditedAt: 'Обновлено 2 дня назад',
    views: 2100,
    booksCount: 15,
    bookmarks: 134,
  },
  {
    id: 'col4',
    title: 'Мировая литература XX века',
    lastEditedAt: 'Обновлено 5 дней назад',
    views: 560,
    booksCount: 10,
    bookmarks: 42,
  },
];
